scrape_configs:
  - job_name: testing
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:8000
