{
 "title": "FlowSpec",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "router", "label": "Router" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "WITH flowspecs_matched_bytes AS (\r\n    SELECT\r\n        timestamp,\r\n        matched_bytes,\r\n        router,\r\n        filter,\r\n        LAG(matched_bytes) OVER by_router AS prev_matched_bytes,\r\n        LAG(timestamp) OVER by_router AS prev_timestamp\r\n    FROM flowspecs\r\n    WHERE $__timeFilter(timestamp) AND router LIKE '%${router}%' AND filter LIKE '%${filter}%'\r\n    WINDOW by_router AS (PARTITION BY router, filter ORDER BY timestamp)\r\n),\r\nflowspecs_matched_bps AS (\r\n  SELECT\r\n      timestamp,\r\n      ((CASE WHEN prev_matched_bytes > matched_bytes THEN 0 ELSE matched_bytes - prev_matched_bytes END) * 8 / GREATEST(extract('epoch' FROM (timestamp - prev_timestamp))::int, 1)) AS bps\r\n  FROM flowspecs_matched_bytes\r\n)\r\nSELECT\r\n    time_bucket('1 minute', timestamp) AS time_1m,\r\n    sum(bps) AS matched\r\nFROM flowspecs_matched_bps\r\nGROUP BY time_1m\r\nORDER BY time_1m ASC"
    },
    {
     "rawSql": "WITH flowspecs_dropped_bytes AS (\r\n    SELECT\r\n        timestamp,\r\n        dropped_bytes,\r\n        router,\r\n        filter,\r\n        LAG(dropped_bytes) OVER by_router AS prev_dropped_bytes,\r\n        LAG(timestamp) OVER by_router AS prev_timestamp\r\n    FROM flowspecs\r\n    WHERE $__timeFilter(timestamp) AND router LIKE '%${router}%' AND filter LIKE '%${filter}%'\r\n    WINDOW by_router AS (PARTITION BY router, filter ORDER BY timestamp)\r\n),\r\nflowspecs_dropped_bps AS (\r\n  SELECT\r\n      timestamp,\r\n      ((CASE WHEN prev_dropped_bytes > dropped_bytes THEN 0 ELSE dropped_bytes - prev_dropped_bytes END) * 8 / GREATEST(extract('epoch' FROM (timestamp - prev_timestamp))::int, 1)) AS bps\r\n  FROM flowspecs_dropped_bytes\r\n)\r\nSELECT\r\n    time_bucket('1 minute', timestamp) AS time_1m,\r\n    sum(bps) AS dropped\r\nFROM flowspecs_dropped_bps\r\nGROUP BY time_1m\r\nORDER BY time_1m ASC"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "WITH flowspecs_matched_packets AS (\r\n    SELECT\r\n        timestamp,\r\n        matched_packets,\r\n        router,\r\n        filter,\r\n        LAG(matched_packets) OVER by_router AS prev_matched_packets,\r\n        LAG(timestamp) OVER by_router AS prev_timestamp\r\n    FROM flowspecs\r\n    WHERE $__timeFilter(timestamp) AND router LIKE '%${router}%' AND filter LIKE '%${filter}%'\r\n    WINDOW by_router AS (PARTITION BY router, filter ORDER BY timestamp)\r\n),\r\nflowspecs_matched_pps AS (\r\n  SELECT\r\n      timestamp,\r\n      ((CASE WHEN prev_matched_packets > matched_packets THEN 0 ELSE matched_packets - prev_matched_packets END) / GREATEST(extract('epoch' FROM (timestamp - prev_timestamp))::int, 1)) AS pps\r\n  FROM flowspecs_matched_packets\r\n)\r\nSELECT\r\n    time_bucket('1 minute', timestamp) AS time_1m,\r\n    sum(pps) AS matched\r\nFROM flowspecs_matched_pps\r\nGROUP BY time_1m\r\nORDER BY time_1m ASC"
    },
    {
     "rawSql": "WITH flowspecs_dropped_packets AS (\r\n    SELECT\r\n        timestamp,\r\n        dropped_packets,\r\n        router,\r\n        filter,\r\n        LAG(dropped_packets) OVER by_router AS prev_dropped_packets,\r\n        LAG(timestamp) OVER by_router AS prev_timestamp\r\n    FROM flowspecs\r\n    WHERE $__timeFilter(timestamp) AND router LIKE '%${router}%' AND filter LIKE '%${filter}%'\r\n    WINDOW by_router AS (PARTITION BY router, filter ORDER BY timestamp)\r\n),\r\nflowspecs_dropped_pps AS (\r\n  SELECT\r\n      timestamp,\r\n      ((CASE WHEN prev_dropped_packets > dropped_packets THEN 0 ELSE dropped_packets - prev_dropped_packets END) / GREATEST(extract('epoch' FROM (timestamp - prev_timestamp))::int, 1)) AS pps\r\n  FROM flowspecs_dropped_packets\r\n)\r\nSELECT\r\n    time_bucket('1 minute', timestamp) AS time_1m,\r\n    sum(pps) AS dropped\r\nFROM flowspecs_dropped_pps\r\nGROUP BY time_1m\r\nORDER BY time_1m ASC"
    }
   ]
  },
  {
   "title": "Filters",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "WITH flowspecs_bytes_and_packets AS (\r\n    SELECT\r\n        timestamp,\r\n        matched_packets,\r\n        dropped_packets,\r\n        matched_bytes,\r\n        dropped_bytes,\r\n        router,\r\n        filter,\r\n        LAG(matched_packets) OVER by_router AS prev_matched_packets,\r\n        LAG(dropped_packets) OVER by_router AS prev_dropped_packets,\r\n        LAG(matched_bytes) OVER by_router AS prev_matched_bytes,\r\n        LAG(dropped_bytes) OVER by_router AS prev_dropped_bytes\r\n    FROM flowspecs\r\n    WHERE $__timeFilter(timestamp) AND router LIKE '%${router}%' AND filter LIKE '%${filter}%'\r\n    WINDOW by_router AS (PARTITION BY router, filter ORDER BY timestamp)\r\n),\r\nflowspecs_diff_bytes_and_packets AS (\r\n  SELECT\r\n      timestamp,\r\n      filter,\r\n      (CASE WHEN prev_matched_packets > matched_packets THEN 0 ELSE matched_packets - prev_matched_packets END) AS diff_matched_packets,\r\n      (CASE WHEN prev_dropped_packets > dropped_packets THEN 0 ELSE dropped_packets - prev_dropped_packets END) AS diff_dropped_packets,\r\n      (CASE WHEN prev_matched_bytes > matched_bytes THEN 0 ELSE matched_bytes - prev_matched_bytes END) AS diff_matched_bytes,\r\n      (CASE WHEN prev_dropped_bytes > dropped_bytes THEN 0 ELSE dropped_bytes - prev_dropped_bytes END) AS diff_dropped_bytes\r\n  FROM flowspecs_bytes_and_packets\r\n)\r\nSELECT\r\n    min(timestamp) AS time_min,\r\n    max(timestamp) AS time_max,\r\n    filter,\r\n    sum(diff_matched_packets) AS matched_packets,\r\n    sum(diff_dropped_packets) AS dropped_packets,\r\n    sum(diff_matched_bytes) AS matched_bytes,\r\n    sum(diff_dropped_bytes) AS dropped_bytes\r\nFROM flowspecs_diff_bytes_and_packets\r\nGROUP BY filter\r\nORDER BY time_max DESC"
    }
   ]
  }
 ]
}