apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: timescaledb:5432
    user: postgres
    jsonData:
      sslmode: disable
      database: postgres
      timescaledb: true
    secureJsonData:
      password: password

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
